M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu24.04.1} date 2026-05-02T22:26:10+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-02T22:26:10+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X154.715Y-84.11
X154.715Y-89.89
M30
